[project]
name = "tlaloc"
version = "0.1.4"
description = "A SaaS metric analysis library for rutine tasks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.3",
    "pyspark>=4.0.1",
    "toolz>=1.1.0",
]

[build-system]
requires = ["hatchling>=1.19"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["tlaloc/**"]

[tool.bumpversion]
current_version = "0.1.4"
commit = true
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "tlaloc/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'


